SBA/SBA.Web/Controllers/BaseController.cs
using SBA.Web.Infrastructure.Alert;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SBA.Web.Controllers
{
    public abstract partial class BaseController : Controller
    {
        public void SetAlert(
            SystemAlert.Type type,
            string message) =>
            TempData["alert"] = SystemAlert.SetAlert(type, message);

        public string GetStatGuid() =>
            HttpContext.Session["_statGuid"]?.ToString();

        public List<string> GetStatTrace() =>
            (List<string>)HttpContext.Session["_statTrace"];
    }
}

SBA/SBA.Web/Controllers/ClientController.cs
using SBA.BOL.Web.Models;
using SBA.BOL.Web.Service;
using System.Collections.Generic;
using System.Configuration;
using System.Net;
using System.Web.Http;

namespace SBA.Web.Controllers
{
    public class ClientController : ApiController
    {
        private readonly IContactService _contactService;
        private readonly IArticleService _articleService;

        public ClientController(
            IContactService contactService,
            IArticleService articleService)
        {
            _contactService = contactService;
            _articleService = articleService;
        }

        [HttpGet]
        public IEnumerable<ContactModel> Messages(string id)
        {
            string appGuid = ConfigurationManager.AppSettings[nameof(appGuid)];

            if (id != appGuid)
                throw new HttpResponseException(HttpStatusCode.Forbidden);

            return _contactService.GetContacts();
        }

        [HttpPost]
        public IHttpActionResult SaveArticle([FromBody]Dictionary<string, string> value) => 
            _articleService.AddArticleFromJson(value) ?
                     Content(HttpStatusCode.OK, true) :
                     Content(HttpStatusCode.Unauthorized, false);
    }
}

SBA/SBA.Web/Controllers/ContactController.cs
using SBA.BOL.Web.Models;
using SBA.BOL.Web.Service;
using SBA.Web.Infrastructure.Filters;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SBA.Web.Controllers
{
    public partial class ContactController : BaseController
    {
        private readonly IContactService _contactService;
        private readonly IClientSocketService _clientSocketService;

        public ContactController(
            IContactService contactService,
            IClientSocketService clientSocketService)
        {
            _contactService = contactService;
            _clientSocketService = clientSocketService;
        }

        [CookieFilter]
        public virtual ActionResult Index() =>
            View();

        [HttpPost]
        public virtual async Task<JsonResult> Send(ContactModel contactModel)
        {
            _contactService.AddContact(contactModel);
            return Json(
                await _clientSocketService.SendUserQuestionToGetSuggestAnswer(contactModel.Message),
                JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public virtual async Task<JsonResult> HandUp(QuestionModel questionModel) => 
            Json(await _clientSocketService.SendHandUp(questionModel));
    }
}

SBA/SBA.Web/Controllers/HomeController.cs
using SBA.BOL.Web.Service;
using SBA.Web.Infrastructure.Filters;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SBA.Web.Controllers
{
    public partial class HomeController : BaseController
    {
        private readonly IClientSocketService _clientSocketService;

        public HomeController(IClientSocketService clientSocketService) =>
            _clientSocketService = clientSocketService;

        [CookieFilter]
        public virtual ActionResult Index() => 
            View();

        [CookieFilter]
        public virtual ActionResult About() =>
            View();

        [HttpGet]
        public virtual async Task<JsonResult> GetFastLinks() => 
            Json(
                await _clientSocketService.SendStatTraceToGetHotLinks(GetStatTrace(), GetStatGuid()),
                JsonRequestBehavior.AllowGet);
    }
}

SBA/SBA.Web/Controllers/NewsController.cs
using SBA.BOL.Web.Service;
using SBA.Web.Infrastructure.Filters;
using System.Web.Mvc;

namespace SBA.Web.Controllers
{
    public partial class NewsController : BaseController
    {
        private readonly IArticleService _articleService;

        public NewsController(IArticleService articleService) =>
            _articleService = articleService;

        [CookieFilter]
        public virtual ActionResult Index(int id = 1) =>
            View(_articleService.GetArticlesByPage(id));

        [CookieFilter]
        public virtual ActionResult Article(int id) =>
            View(_articleService.GetArticleBy(id));
    }
}

SBA/SBA.Web/Views/Home/About.cshtml
@Styles.Render("~/Content/aboutStyle") 

<div class="jumbotron jumbotron-fluid ">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h2 class="display-4">
                    <strong>@ViewBag.Title</strong>
                </h2>
                <p class="lead">
                    <small>Informacje o naszej firmie.</small>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-sm-12 col-lg-12">
		<div class="panel panel-default">
		  <div class="panel-body">
			<p>
				Nasza firma <strong>WebCoding S.A.</strong> rozpoczeła działaność w <strong>2016 roku</strong>. Pomysł założenia firmy powstał już w toku studiów. 
				Pewnego dnia postanowiliśmy zrealizować nasze marzenia i tak od myśli do czynów - założyliśmy <strong>WebCoding S.A.</strong>
			</p>
			<p>
				Na rynku jesteśmy krótko, jednak w minionym roku udało nam się uzyskać certyfikat jakości <strong>ISO 9001</strong> w zakresie projektowania stron internetowych,
				aplikacji mobilnych, jak i oprogramowania dedykowanego. Cały czas dbamy o wyszkolenie naszych pracowników. Od początku działania naszej firmy uzyskaliśmy następujące certyfikaty: 
				<ul>
					<li>
						<strong>Kierownik projektu</strong>
						<p>
							Ten certyfikat uzyskało dwóch pracowników naszej firmy, dzięki czemu obecnie dysponujemy osobami, które mają w pełni świadomość na czym polega
							praca z grupą osób, co usprawniło naszą pracę. 
						</p>
						<p>
							Większa wydajność = szybciej zrelizowane projekty = zadowolenie klienta
						</p>
					</li>
					<li>
						<strong>Certyfikat ISO 9001</strong>
						<p>
							Szkolenie te przeszła cała kadra naszej firmy. Dzięki czemu teraz wszyscy wiedzą na czym polega norma jakości, co zwiększa efektyność pracy. Wszelkie normy i ustalenia
							są jasne dla wszystkich osób w firmie, dzięki czemu każdy łatwiej rozumie to co zrealizowała druga osoba, dzięki czemu nie ma niejasności i nieporozumień w ekipie. 
							ISO 9001 pozwoliło wprowadzić europejski, uniwersalny standrard, który sprecyzował wymagania dotyczące zarządzania pracą firmy.
						<p/>
					</li>
					<li>
						<strong>Design Thinking</strong>
						<p>
							Dwóch pracowników naszej firmy przeszło niniejsze szkolenie, dzieki któremu mogą teraz w lepszy sposób komunikować się z klientem. Są w stanie lepiej zrozumieć drugą osobę, 
							przedstawić mu w jaśniejszy sposób to, co będzie realizowane w ramach projektu. Dzięki temu w szybszym etapie możemy dokonać poprawek, których zarzyczy sobie klient. A co za tym idzie - 
							aplikacja zostanie wykonana w znacznie krótszym czasie.
						<p/>
					</li>
					<li>
						<strong>Microsoft</strong>
						<p>
							Pracownicy naszej firmy posiadają przeszkolenia z oprogramowani firmy <strong>Microsoft</strong>. Każdy z pracowników posiada wiedzę na temat, tego za co jest odpowiedzialny w firmie,
							szkolenia są bowiem szczegółowo dobierane pod to, za co dana osoba jest odpowiedzialna. Są to renomowane certyfikaty, po których odbywają się 
							egzaminy sprawdzające wiedzę. Świadczy to o tym, iż ekipa naszych programistów posiada niezbędny poziom do realizacji aplikacji na najwyższym poziomie.
						<p/>
					</li>
				</ul>
			</p>
		  </div>
		</div>
	</div>
</div>

<div class="container-fluid">
    <div class="row">

        <!-- item -->
        <div class="col-md-4 text-center">
            <div class="panel panel-danger panel-pricing">
                <div class="panel-heading">
                    <i class="fa fa-desktop"></i>
                    <h3>Strony internetowe</h3>
                </div>
                <ul class="list-group text-center">
                    <li class="list-group-item"><i class="fa fa-check"></i> Indywidualny szata graficzna</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Dogłębna analiza potrzeb</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Projekt graficzny</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Adres WWW gratis</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Opieka serwisowa 24/7</li>
                </ul>
                <div class="panel-footer">
					@Html.ActionLink("ZAMÓW!", "../Contact/Index", "Contact", new { @class = "btn btn-lg btn-block btn-danger" })
                </div>
            </div>
        </div>
        <!-- /item -->

        <!-- item -->
        <div class="col-md-4 text-center">
            <div class="panel panel-warning panel-pricing">
                <div class="panel-heading">
                    <i class="fa fa-desktop"></i>
					<h3>Aplikacje mobilne</h3>
                </div>
                <ul class="list-group text-center">
                    <li class="list-group-item"><i class="fa fa-check"></i> Dogłębna analiza wymagań</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Autorskie interfejsy użytkownika</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Jedna aplikacja na 3 platormy: Android, iOS, Windows Phone</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Wdrożenie GooglePlay i AppStore</li>
                </ul>
                <div class="panel-footer">
					@Html.ActionLink("ZAMÓW!", "../Contact/Index", "Home", new { @class = "btn btn-lg btn-block btn-warning" })
                </div>
            </div>
        </div>
        <!-- /item -->

        <!-- item -->
        <div class="col-md-4 text-center">
            <div class="panel panel-success panel-pricing">
                <div class="panel-heading">
                    <i class="fa fa-desktop"></i>
					<h3>Oprogramowanie dedykowane</h3>
                </div>
                <ul class="list-group text-center">
                    <li class="list-group-item"><i class="fa fa-check"></i> Realizacja potrzeb klienta</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Graficzne projekty szaty aplikacji</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Bezpieczeństwo danych</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Wysoka wydajność</li>
                    <li class="list-group-item"><i class="fa fa-check"></i> Darmowe szkolenie dla klienta</li>
                </ul>
                <div class="panel-footer">
					@Html.ActionLink("ZAMÓW!", "../Contact/Index", "Home", new { @class = "btn btn-lg btn-block btn-success" })
                </div>
            </div>
        </div>
        <!-- /item -->

    </div>
</div>

SBA/SBA.Web/Views/Home/Index.cshtml
@Styles.Render("~/Content/homeStyle") @{ ViewBag.Title = "Strona główna"; }
<div class="row">
    <div class="col-md-5 col-lg-5">
        <div class="featured-article">
            <a class="article-link" href="#">
                <img src="http://placehold.it/482x350" alt="" class="thumb">
            </a>
            <div class="block-title">
                <h2>Lorem ipsum dolor asit amet</h2>
                <p class="by-author">Treść artykułu...</p>
                <ul class="list-inline list-unstyled">
                    <li>
                        <span><i class="glyphicon glyphicon-calendar"></i> 2 days, 8 hours </span>
                    </li>
                    <li>|</li>
                    <li>
                        <span>
                            <i class="glyphicon glyphicon-comment"></i> 0 komentarzy</span>
                    </li>
                    <li>|</li>
                    <li>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </li>
                    <li>|</li>
                    <li class="btnShared-container">
                        <a class="btn btn-xs btn-social-icon btn-facebook" href="#" data-toggle="tooltip" title="Share Facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-twitter" href="#" data-toggle="tooltip" title="Share Twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-google" href="#" data-toggle="tooltip" title="Share Google">
                            <i class="fa fa-google"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.featured-article -->
    </div>
    <div class="col-md-7 col-lg-7">
        <ul class="media-list main-list">
            <li class="media">
                <a class="pull-left article-link" href="http://localhost:57934/Contact">
                    <img class="media-object" src="http://placehold.it/150x90" alt="...">
                </a>
                <div class="media-body">
                    <h4 id="head4" class="media-heading clickable">CONTACT</h4>
                    <p id="describe" class="by-author clickable">Treść artykułu...</p>
                </div>
                <hr>
                <ul class="list-inline list-unstyled">
                    <li>
                        <span>
                            <i class="glyphicon glyphicon-calendar"></i> 2 days, 8 hours </span>
                    </li>
                    <li>|</li>
                    <li>
                        <span><i class="glyphicon glyphicon-comment"></i> 0 komentarzy</span>
                    </li>
                    <li>|</li>
                    <li>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </li>
                    <li>|</li>
                    <li class="btnShared-container">
                        <a class="btn btn-xs btn-social-icon btn-facebook" href="#" data-toggle="tooltip" title="Share Facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-twitter" href="#" data-toggle="tooltip" title="Share Twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-google" href="#" data-toggle="tooltip" title="Share Google">
                            <i class="fa fa-google"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="media">
                <a class="pull-left article-link" href="#">
                    <img class="media-object" src="http://placehold.it/150x90" alt="...">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Lorem ipsum dolor asit amet</h4>
                    <p class="by-author">Treść artykułu...</p>
                </div>
                <hr>
                <ul class="list-inline list-unstyled">
                    <li>
                        <span>
                            <i class="glyphicon glyphicon-calendar"></i> 2 days, 8 hours </span>
                    </li>
                    <li>|</li>
                    <li>
                        <span><i class="glyphicon glyphicon-comment"></i> 0 komentarzy</span>
                    </li>
                    <li>|</li>
                    <li>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </li>
                    <li>|</li>
                    <li class="btnShared-container">
                        <a class="btn btn-xs btn-social-icon btn-facebook" href="#" data-toggle="tooltip" title="Share Facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-twitter" href="#" data-toggle="tooltip" title="Share Twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-google" href="#" data-toggle="tooltip" title="Share Google">
                            <i class="fa fa-google"></i>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="media">
                <a class="pull-left article-link" href="#">
                    <img class="media-object" src="http://placehold.it/150x90" alt="...">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Lorem ipsum dolor asit amet</h4>
                    <p class="by-author">Treść artykułu...</p>
                </div>
                <hr>
                <ul class="list-inline list-unstyled">
                    <li>
                        <span>
                            <i class="glyphicon glyphicon-calendar"></i> 2 days, 8 hours </span>
                    </li>
                    <li>|</li>
                    <li>
                        <span><i class="glyphicon glyphicon-comment"></i> 0 komentarzy</span>
                    </li>
                    <li>|</li>
                    <li>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star-empty"></span>
                    </li>
                    <li>|</li>
                    <li class="btnShared-container">
                        <a class="btn btn-xs btn-social-icon btn-facebook" href="#" data-toggle="tooltip" title="Share Facebook">
                            <i class="fa fa-facebook"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-twitter" href="#" data-toggle="tooltip" title="Share Twitter">
                            <i class="fa fa-twitter"></i>
                        </a>
                        <a class="btn btn-xs btn-social-icon btn-google" href="#" data-toggle="tooltip" title="Share Google">
                            <i class="fa fa-google"></i>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

SBA/SBA.Web/Views/News/Article.cshtml
@using SBA.BOL.Web.Models
@model ArticleModel

@{ ViewBag.Title = Model.Title; }

<h1>@Model.Title</h1>
<hr />
<h4><i>@Model.InsertTime</i></h4>
<p>
    @Html.Raw(Model.Content)
</p>

SBA/SBA.Web/Views/Shared/_Layout.cshtml
@using SBA.Web.Infrastructure.Alert

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — WebCoding S.A</title>
    @Styles.Render("~/Content/mainCss")
	@Styles.Render("~/Content/mainLess")
    @Scripts.Render("~/bundles/modernizr")
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="loader" id="loadingSpinner" style="display: none;">
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebCoding S.A.", "Index", "Home", null, new { @class = "navbar-brand"})
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("O nas", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Aktualności", "Index", "News")
                    </li>
                    <li>
                        @Html.ActionLink("Kontakt", "Index", "Contact")
                    </li>
                </ul>

				<div class="col-xs-12 col-lg-4 col-sm-5 col-md-4 pull-right">
					<form class="navbar-form" role="search">
					<div class="input-group" id="searchInputGroup">
						<input type="text" class="form-control" placeholder="Search" name="searchInput" id="searchInput">
						<div class="input-group-btn">
							<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
						</div>
					</div>
					</form>
				</div>

            </div>
        </div>
    </nav>
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">WebCoding S.A.</h1>
					<p class="taglineDescribe">Bo programowanie to nasza pasja...</p>
				</div>
            </div>
        </div>
    </header>
    <div class="container">
        <br />
        <div id="tempMessage">
            @Html.RenderAlert()
        </div>
        @RenderBody()
    </div>
    <div id="containerLinks" class="fixedLinksContainer">
        <h3 class="text-center">Szybkie linki</h3>
        <div id="linksSpinner" class="text-center">
            <img src="~/Content/Images/loading.svg" />        
        </div>
        <div id="links"></div>
        <button id="fixedCloseBtn" type="button" class="btn btn-primary">Zamknij</button>
    </div>
	<aside id="arrowUp">
		<div class="arrow bounce">
		  <a class="fa fa-arrow-up fa-3x" href="#top"></a>
		</div>
	</aside>

	<footer class="page-footer font-small stylish-color-dark pt-4 mt-4 bg-dark">

			<!--Footer Links-->
			<div class="container mt-5 mb-4">
				<div class="row mt-3">

					<!--First column-->
					<div class="col-md-4 col-lg-4 col-md-offset-0 col-lg-offset-0 colFooter">
						<h6 class="text-uppercase font-weight-bold ">
							<strong>WebCoding S.A.</strong>
						</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto h6hr">
						<p>  Nasza wspaniała firma zajmuje się tym i tym. Jesteśmy obecni już na rynku od 2010 roku. Nasze projekty były chwalone, a realizacja z klientem zawsze przebiegała pomyślnie. <br>Zachęcamy do skorzystania z naszych usług!</p>
					</div>
					<!--/.First column-->

					<!--Second column-->
					<div class="col-md-2 col-lg-2 col-md-offset-0 col-lg-offset-0 mx-auto mb-4 colFooter">
						<h6 class="text-uppercase font-weight-bold">
							<strong>Produkty</strong>
						</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto h6hr">
						<p>
							<a href="#!">MDBootstrap</a>
						</p>
						<p>
							<a href="#!">MDWordPress</a>
						</p>
						<p>
							<a href="#!">BrandFlow</a>
						</p>
						<p>
							<a href="#!">Bootstrap Angular</a>
						</p>
					</div>
					<!--/.Second column-->

					<!--Third column-->
					<div class="col-md-3 col-lg-3 col-md-offset-0 col-lg-offset-0 mx-auto mb-4 colFooter">
						<h6 class="text-uppercase font-weight-bold">
							<strong>Szybkie linki</strong>
						</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto h6hr" >
						<p>
							<a href="#!">Your Account</a>
						</p>
						<p>
							<a href="#!">Become an Affiliate</a>
						</p>
						<p>
							<a href="#!">Shipping Rates</a>
						</p>
						<p>
							<a href="#!">Help</a>
						</p>
					</div>
					<!--/.Third column-->

					<!--Fourth column-->
					<div class="col-md-3 col-lg-3 col-md-offset-0 col-lg-offset-0 colFooter">
						<h6 class="text-uppercase font-weight-bold">
							<strong>Kontakt</strong>
						</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto h6hr" >
						<p>
							<i class="glyphicon glyphicon-home" style="margin-right:20px"></i> Białystok, Polska</p>
						<p>
							<i class="glyphicon glyphicon-envelope" style="margin-right:20px"></i> info@example.com</p>
						<p>
							<i class="glyphicon glyphicon-earphone" style="margin-right:20px"></i> + 01 234 567 88</p>
						<p>
							<i class="glyphicon glyphicon-print" style="margin-right:20px"></i> + 01 234 567 89</p>
					</div>
					<!--/.Fourth column-->

				</div>
			</div>
		 <!--/.Footer Links-->

		<hr>

		<!--Social buttons-->
		<!--
		<div class="text-center">
			<ul class="list-unstyled list-inline">
				<li class="list-inline-item">
					<a class="btn-floating btn-sm btn-fb mx-1">
						<i class="fa fa-facebook"> </i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="btn-floating btn-sm btn-tw mx-1">
						<i class="fa fa-twitter"> </i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="btn-floating btn-sm btn-gplus mx-1">
						<i class="fa fa-google-plus"> </i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="btn-floating btn-sm btn-li mx-1">
						<i class="fa fa-linkedin"> </i>
					</a>
				</li>
				<li class="list-inline-item">
					<a class="btn-floating btn-sm btn-dribbble mx-1">
						<i class="fa fa-dribbble"> </i>
					</a>
				</li>
			</ul>
		</div>
		-->
		<!--/.Social buttons-->

		<iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d76608.78054593953!2d23.086026499746943!3d53.12770770612764!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ffc048f41971d%3A0x72317dcc8bf07b2c!2s15-001+Bia%C5%82ystok!5e0!3m2!1spl!2spl!4v1520942157613"  frameborder="0" allowfullscreen></iframe>

		<hr>

		<!--Copyright-->
		<div class="footer-copyright py-3 text-center bg-black font-color-gray">
			© 2018 Copyright
		</div>
		<!--/.Copyright-->

	</footer>                      

    @Scripts.Render("~/bundles/mainJs")
    @RenderSection("scripts", required: false)
</body>
</html>